Project 1 wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search", views.search, name="search"),
    path("new", views.new, name="new"),
    path("edit", views.edit, name="edit"),
    path("random", views.random, name="random"),
]

Project 1 wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

Project 1 wiki/wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from . import util
from random import choice
import markdown2


def index(request):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})


def entry(request, title):
    content = util.get_entry(title)
    if content is None:
        return render(request, "encyclopedia/error.html", {"message": "Page not found"})
    markdown_content = markdown2.markdown(content)
    return render(
        request,
        "encyclopedia/entry.html",
        {"title": title, "content": markdown_content},
    )


def search(request):
    query = request.GET.get("q", "").lower()
    entries = util.list_entries()
    if query in [entry.lower() for entry in entries]:
        return redirect("entry", title=query)

    results = list(sorted([entry for entry in entries if query in entry.lower()]))
    return render(
        request, "encyclopedia/search.html", {"results": results, "query": query}
    )


def new(request):
    if request.method == "POST":
        title = request.POST["title"]
        content = request.POST["content"]

        if util.get_entry(title):
            messages.error(request, f"Entry '{title}' already exists")
            return render(request, "encyclopedia/new.html")

        util.save_entry(title, content)
        return redirect("encyclopedia:entry", title=title)

    return render(request, "encyclopedia/new.html")


def edit(request):
    if request.method == "POST":
        title = request.POST["title"]
        content = request.POST["content"]
        util.save_entry(title, content)
        return redirect("encyclopedia:entry", title=title)

    title = request.GET.get("title", "")
    content = util.get_entry(title)
    return render(
        request, "encyclopedia/edit.html", {"title": title, "content": content}
    )


def random(request):
    entries = util.list_entries()
    random_entry = choice(entries)
    return redirect("encyclopedia:entry", title=random_entry)

Project 1 wiki/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit entry
{% endblock %}

{% block body %}
    <h1>Edit entry</h1>
    <form action="{% url 'encyclopedia:edit' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="title" value="{{ title }}" required>
        <textarea name="content" required>{{ content }}</textarea>
        <button type="submit">Save changes</button>
    </form>
{% endblock %}

Project 1 wiki/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>
    {{ content|safe }}
    <form action="{% url 'encyclopedia:edit' %}" method="GET">
        <input type="hidden" name="title" value="{{ title }}">
        <button type="submit">Edit entry</button>
    </form>
{% endblock %}

Project 1 wiki/wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    <h1>Error: {{ message }}</h1>
{% endblock %}

Project 1 wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

Project 1 wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Project 1 wiki/wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New page
{% endblock %}

{% block body %}
    <h1>Create new page</h1>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <form action="{% url 'encyclopedia:new' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="title" placeholder="Title" required>
        <textarea name="content" placeholder="Enter your Markdown content here" required></textarea>
        <button type="submit">Save Page</button>
    </form>
{% endblock %}

Project 1 wiki/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>Search results of "{{ query }}"</h1>
    <ul>
        {% for result in results %}
            <li><a href="{% url 'encyclopedia:entry' title=result %}">{{ result }}</a></li>
        {% empty %}
            <p>No page found</p>
        {% endfor %}
    </ul>
{% endblock %}